version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: pedidosacemi
    restart: unless-stopped
    ports:
      - "8183:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_URL: https://orders.acemispain.com
